#ifndef QING_MACROS_H
#define QING_MACROS_H

#define QING_FILTER_INTENSITY_RANGE 256
#define QING_FILTER_SPATIAL_RANGE   256
#define QING_PI 3.14159265
#define QING_DEBUG_FLAG_STRING  "COOLCOOLCOOL"

#endif // QING_MACROS_H
